name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      

      - name: build docker-compose
        run: |
          docker-compose up -d --build
          


      
