name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v2

      - name: exec react test
        run: |
          cd react/react-application
          npm run test
      
      - name: build docker-compose
        run: |
          docker-compose up -d --build
          


      
